import { EXPANDED_ITEMS } from "./expanded-items";
import type { Item } from "../types";
import type { SeedItem } from "./types";

export const SEED_ITEMS: SeedItem[] = [
  // Dairy (10 items)
  {
    item: {
      id: "milk-2pct-4l",
      name: "2% milk",
      category: "dairy",
      sizeQty: 4,
      unit: "L",
      sizeLabel: "4 L",
      artKey: "milk",
      aliases: [
        "2% milk",
        "milk",
        "2 percent milk",
        "partly skimmed milk",
        "4l milk",
        "2l milk",
        "1l milk",
        "2% milk 2l",
        "2% milk 4l",
      ],
      searchQuery: "2% milk 4 L",
    },
    basePrice: 6.39,
  },
  {
    item: {
      id: "milk-homo-2l",
      name: "Homogenized milk",
      category: "dairy",
      sizeQty: 2,
      unit: "L",
      sizeLabel: "2 L",
      artKey: "milk",
      aliases: [
        "homo milk",
        "homogenized milk",
        "whole milk",
        "3.25% milk",
        "homo milk 4l",
        "homo milk 2l",
        "4l milk",
        "2l milk",
      ],
      searchQuery: "homogenized milk 2 L",
    },
    basePrice: 4.79,
  },
  {
    item: {
      id: "butter-salted-454g",
      name: "Salted butter",
      category: "dairy",
      sizeQty: 0.454,
      unit: "kg",
      sizeLabel: "454 g",
      artKey: "butter",
      aliases: ["butter", "salted butter", "butter brick"],
      searchQuery: "salted butter 454 g",
    },
    basePrice: 6.1,
    saleProfile: { saveon: "perpetual" },
  },
  {
    item: {
      id: "eggs-large-12",
      name: "Large eggs",
      category: "dairy",
      sizeQty: 1,
      unit: "dozen",
      sizeLabel: "dozen",
      artKey: "eggs",
      aliases: ["eggs", "large eggs", "dozen eggs", "white eggs"],
      searchQuery: "large eggs 12",
    },
    basePrice: 4.6,
  },
  {
    item: {
      id: "cheddar-old-400g",
      name: "Old cheddar",
      category: "dairy",
      sizeQty: 0.4,
      unit: "kg",
      sizeLabel: "400 g",
      artKey: "cheese",
      aliases: ["cheddar", "old cheddar", "cheese block", "cheddar cheese"],
      searchQuery: "old cheddar cheese 400 g",
    },
    basePrice: 7.49,
  },
  {
    item: {
      id: "mozzarella-340g",
      name: "Mozzarella",
      category: "dairy",
      sizeQty: 0.34,
      unit: "kg",
      sizeLabel: "340 g",
      artKey: "cheese",
      aliases: ["mozzarella", "mozzarella cheese", "pizza cheese"],
      searchQuery: "mozzarella cheese 340 g",
    },
    basePrice: 5.99,
  },
  {
    item: {
      id: "greek-yogurt-plain",
      name: "Plain Greek yogurt",
      category: "dairy",
      sizeQty: 0.5,
      unit: "kg",
      sizeLabel: "500 g",
      artKey: "yogurt",
      aliases: ["greek yogurt", "plain greek yogurt", "plain yogurt"],
      searchQuery: "plain greek yogurt 500 g",
    },
    basePrice: 6.1,
  },
  {
    item: {
      id: "yogurt-vanilla-650g",
      name: "Vanilla yogurt",
      category: "dairy",
      sizeQty: 0.65,
      unit: "kg",
      sizeLabel: "650 g",
      artKey: "yogurt",
      aliases: ["vanilla yogurt", "yogurt", "vanilla tub"],
      searchQuery: "vanilla yogurt 650 g",
    },
    basePrice: 4.49,
  },
  {
    item: {
      id: "sour-cream-500ml",
      name: "Sour cream",
      category: "dairy",
      sizeQty: 0.5,
      unit: "L",
      sizeLabel: "500 mL",
      artKey: "sourcream",
      aliases: ["sour cream", "14% sour cream", "crema"],
      searchQuery: "sour cream 500 mL",
    },
    basePrice: 3.49,
  },
  {
    item: {
      id: "cream-cheese-250g",
      name: "Cream cheese",
      category: "dairy",
      sizeQty: 0.25,
      unit: "kg",
      sizeLabel: "250 g",
      artKey: "butter",
      aliases: ["cream cheese", "cream cheese brick", "spreadable cream cheese"],
      searchQuery: "cream cheese 250 g",
    },
    basePrice: 4.29,
  },

  // Bakery (8 items)
  {
    item: {
      id: "flour-ap-10kg",
      name: "All-purpose flour",
      category: "bakery",
      sizeQty: 10,
      unit: "kg",
      sizeLabel: "10 kg",
      artKey: "flour",
      aliases: ["flour", "all purpose flour", "white flour", "ap flour"],
      searchQuery: "all purpose flour 10 kg",
    },
    basePrice: 18.5,
  },
  {
    item: {
      id: "flour-ap-2-5kg",
      name: "All-purpose flour",
      category: "bakery",
      sizeQty: 2.5,
      unit: "kg",
      sizeLabel: "2.5 kg",
      artKey: "flour",
      aliases: ["flour", "all purpose flour", "white flour", "ap flour 2.5kg"],
      searchQuery: "all purpose flour 2.5 kg",
    },
    basePrice: 6.49,
  },
  {
    item: {
      id: "flour-ww-2-5kg",
      name: "Whole wheat flour",
      category: "bakery",
      sizeQty: 2.5,
      unit: "kg",
      sizeLabel: "2.5 kg",
      artKey: "flour",
      aliases: ["whole wheat flour", "ww flour", "wheat flour"],
      searchQuery: "whole wheat flour 2.5 kg",
    },
    basePrice: 6.99,
  },
  {
    item: {
      id: "bread-white-675g",
      name: "White sandwich bread",
      category: "bakery",
      sizeQty: 0.675,
      unit: "kg",
      sizeLabel: "675 g",
      artKey: "bread",
      aliases: ["white bread", "sandwich bread", "sliced bread"],
      searchQuery: "white sandwich bread 675 g",
    },
    basePrice: 3.29,
  },
  {
    item: {
      id: "bread-ww-675g",
      name: "Whole wheat bread",
      category: "bakery",
      sizeQty: 0.675,
      unit: "kg",
      sizeLabel: "675 g",
      artKey: "bread",
      aliases: ["whole wheat bread", "brown bread", "wheat bread"],
      searchQuery: "whole wheat bread 675 g",
    },
    basePrice: 3.49,
  },
  {
    item: {
      id: "sugar-2kg",
      name: "Granulated sugar",
      category: "bakery",
      sizeQty: 2,
      unit: "kg",
      sizeLabel: "2 kg",
      artKey: "sugar",
      aliases: ["sugar", "white sugar", "granulated sugar"],
      searchQuery: "granulated white sugar 2 kg",
    },
    basePrice: 3.99,
  },
  {
    item: {
      id: "oats-1kg",
      name: "Large flake oats",
      category: "bakery",
      sizeQty: 1,
      unit: "kg",
      sizeLabel: "1 kg",
      artKey: "oats",
      aliases: ["oats", "rolled oats", "large flake oats", "oatmeal"],
      searchQuery: "large flake oats 1 kg",
    },
    basePrice: 3.79,
  },
  {
    item: {
      id: "bagels-6",
      name: "Plain bagels",
      category: "bakery",
      sizeQty: 6,
      unit: "each",
      sizeLabel: "6 pack",
      artKey: "bagel",
      aliases: ["bagels", "plain bagels", "6 pack bagels"],
      searchQuery: "plain bagels 6 pack",
    },
    basePrice: 3.99,
  },

  // Pantry (10 items)
  {
    item: {
      id: "spaghetti-900g",
      name: "Spaghetti",
      category: "pantry",
      sizeQty: 0.9,
      unit: "kg",
      sizeLabel: "900 g",
      artKey: "pasta",
      aliases: ["spaghetti", "pasta", "noodles"],
      searchQuery: "spaghetti 900 g",
    },
    basePrice: 2.55,
  },
  {
    item: {
      id: "penne-900g",
      name: "Penne",
      category: "pantry",
      sizeQty: 0.9,
      unit: "kg",
      sizeLabel: "900 g",
      artKey: "pasta",
      aliases: ["penne", "penne rigate", "pasta"],
      searchQuery: "penne rigate 900 g",
    },
    basePrice: 2.55,
  },
  {
    item: {
      id: "rice-long-8kg",
      name: "Long grain rice",
      category: "pantry",
      sizeQty: 8,
      unit: "kg",
      sizeLabel: "8 kg",
      artKey: "rice",
      aliases: ["rice", "white rice", "long grain rice"],
      searchQuery: "white long grain rice 8 kg",
    },
    basePrice: 17.99,
  },
  {
    item: {
      id: "rice-jasmine-8kg",
      name: "Jasmine rice",
      category: "pantry",
      sizeQty: 8,
      unit: "kg",
      sizeLabel: "8 kg",
      artKey: "rice",
      aliases: ["jasmine rice", "thai jasmine rice", "fragrant rice", "rice"],
      searchQuery: "jasmine rice 8 kg",
    },
    basePrice: 19.99,
  },
  {
    item: {
      id: "canola-oil-3l",
      name: "Canola oil",
      category: "pantry",
      sizeQty: 3,
      unit: "L",
      sizeLabel: "3 L",
      artKey: "oil",
      aliases: ["canola oil", "cooking oil", "vegetable oil"],
      searchQuery: "canola oil 3 L",
    },
    basePrice: 9.99,
  },
  {
    item: {
      id: "peanut-butter-1kg",
      name: "Peanut butter",
      category: "pantry",
      sizeQty: 1,
      unit: "kg",
      sizeLabel: "1 kg",
      artKey: "jar",
      aliases: ["peanut butter", "smooth peanut butter", "pb"],
      searchQuery: "smooth peanut butter 1 kg",
    },
    basePrice: 6.49,
  },
  {
    item: {
      id: "tomatoes-canned-796ml",
      name: "Diced tomatoes",
      category: "pantry",
      sizeQty: 0.796,
      unit: "L",
      sizeLabel: "796 mL",
      artKey: "can",
      aliases: ["canned tomatoes", "diced tomatoes", "tomatoes"],
      searchQuery: "diced tomatoes 796 mL",
    },
    basePrice: 1.99,
  },
  {
    item: {
      id: "black-beans-540ml",
      name: "Black beans",
      category: "pantry",
      sizeQty: 0.54,
      unit: "L",
      sizeLabel: "540 mL",
      artKey: "can",
      aliases: ["black beans", "canned beans", "frijoles"],
      searchQuery: "black beans 540 mL",
    },
    basePrice: 1.49,
  },
  {
    item: {
      id: "pasta-sauce-650ml",
      name: "Tomato pasta sauce",
      category: "pantry",
      sizeQty: 0.65,
      unit: "L",
      sizeLabel: "650 mL",
      artKey: "jar",
      aliases: ["pasta sauce", "marinara", "tomato sauce", "spaghetti sauce"],
      searchQuery: "tomato pasta sauce 650 mL",
    },
    basePrice: 2.99,
  },
  {
    item: {
      id: "chicken-broth-900ml",
      name: "Chicken broth",
      category: "pantry",
      sizeQty: 0.9,
      unit: "L",
      sizeLabel: "900 mL",
      artKey: "carton",
      aliases: ["chicken broth", "chicken stock", "broth"],
      searchQuery: "chicken broth 900 mL",
    },
    basePrice: 2.49,
  },

  // Produce (12 items)
  {
    item: {
      id: "bananas-kg",
      name: "Bananas",
      category: "produce",
      sizeQty: 1,
      unit: "kg",
      sizeLabel: "per kg",
      artKey: "banana",
      aliases: ["bananas", "banana", "yellow bananas"],
      searchQuery: "bananas",
    },
    basePrice: 1.7,
  },
  {
    item: {
      id: "apples-gala-kg",
      name: "Gala apples",
      category: "produce",
      sizeQty: 1,
      unit: "kg",
      sizeLabel: "per kg",
      artKey: "apple",
      aliases: ["apples", "gala apples", "red apples"],
      searchQuery: "gala apples",
    },
    basePrice: 4.39,
  },
  {
    item: {
      id: "carrots-907g",
      name: "Carrots",
      category: "produce",
      sizeQty: 0.907,
      unit: "kg",
      sizeLabel: "2 lb bag",
      artKey: "carrot",
      aliases: ["carrots", "whole carrots", "bag of carrots"],
      searchQuery: "carrots 2 lb",
    },
    basePrice: 2.49,
  },
  {
    item: {
      id: "potatoes-russet-4-54kg",
      name: "Russet potatoes",
      category: "produce",
      sizeQty: 4.54,
      unit: "kg",
      sizeLabel: "10 lb bag",
      artKey: "potato",
      aliases: ["potatoes", "russet potatoes", "baking potatoes"],
      searchQuery: "russet potatoes 10 lb",
    },
    basePrice: 5.99,
  },
  {
    item: {
      id: "onions-yellow-1-36kg",
      name: "Yellow onions",
      category: "produce",
      sizeQty: 1.36,
      unit: "kg",
      sizeLabel: "3 lb bag",
      artKey: "onion",
      aliases: ["onions", "yellow onions", "cooking onions"],
      searchQuery: "yellow onions 3 lb",
    },
    basePrice: 3.49,
  },
  {
    item: {
      id: "tomatoes-roma-kg",
      name: "Roma tomatoes",
      category: "produce",
      sizeQty: 1,
      unit: "kg",
      sizeLabel: "per kg",
      artKey: "tomato",
      aliases: ["roma tomatoes", "plum tomatoes", "tomatoes"],
      searchQuery: "roma tomatoes",
    },
    basePrice: 4.39,
  },
  {
    item: {
      id: "romaine-3",
      name: "Romaine hearts",
      category: "produce",
      sizeQty: 3,
      unit: "each",
      sizeLabel: "3 pack",
      artKey: "lettuce",
      aliases: ["romaine hearts", "lettuce", "romaine lettuce"],
      searchQuery: "romaine hearts 3 pack",
    },
    basePrice: 4.49,
  },
  {
    item: {
      id: "strawberries-454g",
      name: "Strawberries",
      category: "produce",
      sizeQty: 0.454,
      unit: "kg",
      sizeLabel: "454 g",
      artKey: "berries",
      aliases: ["strawberries", "fresh strawberries", "berries"],
      searchQuery: "fresh strawberries 454 g",
    },
    basePrice: 4.6,
    seasonal: true,
  },
  {
    item: {
      id: "blueberries-510g",
      name: "Blueberries",
      category: "produce",
      sizeQty: 0.51,
      unit: "kg",
      sizeLabel: "510 g",
      artKey: "berries",
      aliases: ["blueberries", "fresh blueberries", "berries"],
      searchQuery: "fresh blueberries 510 g",
    },
    basePrice: 5.99,
    seasonal: true,
  },
  {
    item: {
      id: "broccoli-kg",
      name: "Broccoli crowns",
      category: "produce",
      sizeQty: 1,
      unit: "kg",
      sizeLabel: "per kg",
      artKey: "broccoli",
      aliases: ["broccoli", "broccoli crowns", "fresh broccoli"],
      searchQuery: "broccoli crowns",
    },
    basePrice: 4.39,
  },
  {
    item: {
      id: "cucumber-english",
      name: "English cucumber",
      category: "produce",
      sizeQty: 1,
      unit: "each",
      sizeLabel: "each",
      artKey: "cucumber",
      aliases: ["cucumber", "english cucumber", "long english cucumber"],
      searchQuery: "english cucumber",
    },
    basePrice: 1.79,
  },
  {
    item: {
      id: "avocados-4",
      name: "Avocados",
      category: "produce",
      sizeQty: 4,
      unit: "each",
      sizeLabel: "4 pack",
      artKey: "avocado",
      aliases: ["avocados", "haas avocados", "bag of avocados"],
      searchQuery: "avocados 4 pack",
    },
    basePrice: 4.99,
  },
  // Expanded catalogue: Hammer-driven staples (dairy, bakery, pantry, produce)
  {
    item: {
      id: "milk-1pct-4l",
      name: "1% milk",
      category: "dairy",
      sizeQty: 4,
      unit: "L",
      sizeLabel: "4 L",
      artKey: "milk",
      aliases: ["1% milk", "1 percent milk"],
      searchQuery: "1% milk 4 L",
    },
    basePrice: 6.2,
  },
  {
    item: {
      id: "milk-1pct-2l",
      name: "1% milk (2 L)",
      category: "dairy",
      sizeQty: 2,
      unit: "L",
      sizeLabel: "2 L",
      artKey: "milk",
      aliases: ["1% milk", "1 percent milk"],
      searchQuery: "1% milk 2 L",
    },
    basePrice: 4.4,
  },
  {
    item: {
      id: "milk-skim-4l",
      name: "Skim milk",
      category: "dairy",
      sizeQty: 4,
      unit: "L",
      sizeLabel: "4 L",
      artKey: "milk",
      aliases: ["skim milk", "skimmed milk"],
      searchQuery: "skim milk 4 L",
    },
    basePrice: 6.0,
  },
  {
    item: {
      id: "milk-skim-2l",
      name: "Skim milk (2 L)",
      category: "dairy",
      sizeQty: 2,
      unit: "L",
      sizeLabel: "2 L",
      artKey: "milk",
      aliases: ["skim milk", "skimmed milk"],
      searchQuery: "skim milk 2 L",
    },
    basePrice: 4.2,
  },
  {
    item: {
      id: "milk-homo-4l",
      name: "Homogenized milk (4 L)",
      category: "dairy",
      sizeQty: 4,
      unit: "L",
      sizeLabel: "4 L",
      artKey: "milk",
      aliases: ["homo milk", "homogenized milk", "whole milk", "3.25% milk"],
      searchQuery: "homogenized milk 4 L",
    },
    basePrice: 7.0,
  },
  {
    item: {
      id: "milk-2pct-2l",
      name: "2% milk (2 L)",
      category: "dairy",
      sizeQty: 2,
      unit: "L",
      sizeLabel: "2 L",
      artKey: "milk",
      aliases: ["2% milk", "2 percent milk"],
      searchQuery: "2% milk 2 L",
    },
    basePrice: 4.6,
  },
  {
    item: {
      id: "milk-lactosefree-2l",
      name: "Lactose-free milk",
      category: "dairy",
      sizeQty: 2,
      unit: "L",
      sizeLabel: "2 L",
      artKey: "milk",
      aliases: ["lactose free milk", "lactose-free milk"],
      searchQuery: "lactose free milk 2 L",
    },
    basePrice: 5.6,
  },
  {
    item: {
      id: "milk-almond-1-89l",
      name: "Almond milk",
      category: "dairy",
      sizeQty: 1.89,
      unit: "L",
      sizeLabel: "1.89 L",
      artKey: "carton",
      aliases: ["almond milk", "almond beverage"],
      searchQuery: "almond milk 1.89 L",
    },
    basePrice: 4.2,
  },
  {
    item: {
      id: "milk-soy-1-89l",
      name: "Soy milk",
      category: "dairy",
      sizeQty: 1.89,
      unit: "L",
      sizeLabel: "1.89 L",
      artKey: "carton",
      aliases: ["soy milk", "soy beverage"],
      searchQuery: "soy milk 1.89 L",
    },
    basePrice: 3.9,
  },
  {
    item: {
      id: "milk-oat-1-89l",
      name: "Oat milk",
      category: "dairy",
      sizeQty: 1.89,
      unit: "L",
      sizeLabel: "1.89 L",
      artKey: "carton",
      aliases: ["oat milk", "oat beverage"],
      searchQuery: "oat milk 1.89 L",
    },
    basePrice: 4.8,
  },
  {
    item: {
      id: "cream-35-473ml",
      name: "Whipping cream",
      category: "dairy",
      sizeQty: 0.473,
      unit: "L",
      sizeLabel: "473 mL",
      artKey: "carton",
      aliases: ["whipping cream", "35% cream", "heavy cream"],
      searchQuery: "whipping cream 473 mL",
    },
    basePrice: 4.9,
  },
  {
    item: {
      id: "cream-18-473ml",
      name: "Coffee cream 18%",
      category: "dairy",
      sizeQty: 0.473,
      unit: "L",
      sizeLabel: "473 mL",
      artKey: "carton",
      aliases: ["18% cream", "coffee cream"],
      searchQuery: "18% cream 473 mL",
    },
    basePrice: 4.3,
  },
  {
    item: {
      id: "cheddar-medium-400g",
      name: "Medium cheddar",
      category: "dairy",
      sizeQty: 0.4,
      unit: "kg",
      sizeLabel: "400 g",
      artKey: "cheese",
      aliases: ["medium cheddar", "medium cheddar cheese"],
      searchQuery: "medium cheddar 400 g",
    },
    basePrice: 7.0,
  },
  {
    item: {
      id: "cheddar-mild-400g",
      name: "Mild cheddar",
      category: "dairy",
      sizeQty: 0.4,
      unit: "kg",
      sizeLabel: "400 g",
      artKey: "cheese",
      aliases: ["mild cheddar", "mild cheddar cheese"],
      searchQuery: "mild cheddar 400 g",
    },
    basePrice: 7.0,
  },
  {
    item: {
      id: "feta-200g",
      name: "Feta cheese",
      category: "dairy",
      sizeQty: 0.2,
      unit: "kg",
      sizeLabel: "200 g",
      artKey: "cheese",
      aliases: ["feta", "feta cheese"],
      searchQuery: "feta cheese 200 g",
    },
    basePrice: 4.6,
  },
  {
    item: {
      id: "cottage-cheese-500g",
      name: "Cottage cheese",
      category: "dairy",
      sizeQty: 0.5,
      unit: "kg",
      sizeLabel: "500 g",
      artKey: "cheese",
      aliases: ["cottage cheese"],
      searchQuery: "cottage cheese 500 g",
    },
    basePrice: 4.5,
  },
  {
    item: {
      id: "ricotta-475g",
      name: "Ricotta cheese",
      category: "dairy",
      sizeQty: 0.475,
      unit: "kg",
      sizeLabel: "475 g",
      artKey: "cheese",
      aliases: ["ricotta", "ricotta cheese"],
      searchQuery: "ricotta cheese 475 g",
    },
    basePrice: 5.2,
  },
  {
    item: {
      id: "butter-unsalted-454g",
      name: "Unsalted butter",
      category: "dairy",
      sizeQty: 0.454,
      unit: "kg",
      sizeLabel: "454 g",
      artKey: "butter",
      aliases: ["unsalted butter"],
      searchQuery: "unsalted butter 454 g",
    },
    basePrice: 6.4,
  },
  {
    item: {
      id: "margarine-454g",
      name: "Margarine",
      category: "dairy",
      sizeQty: 0.454,
      unit: "kg",
      sizeLabel: "454 g",
      artKey: "butter",
      aliases: ["margarine", "tub margarine"],
      searchQuery: "margarine 454 g",
    },
    basePrice: 4.6,
  },
  {
    item: {
      id: "yogurt-plain-650g",
      name: "Plain yogurt",
      category: "dairy",
      sizeQty: 0.65,
      unit: "kg",
      sizeLabel: "650 g",
      artKey: "yogurt",
      aliases: ["plain yogurt"],
      searchQuery: "plain yogurt 650 g",
    },
    basePrice: 4.0,
  },
  {
    item: {
      id: "yogurt-strawberry-650g",
      name: "Strawberry yogurt",
      category: "dairy",
      sizeQty: 0.65,
      unit: "kg",
      sizeLabel: "650 g",
      artKey: "yogurt",
      aliases: ["strawberry yogurt"],
      searchQuery: "strawberry yogurt 650 g",
    },
    basePrice: 4.3,
  },
  {
    item: {
      id: "eggs-large-18",
      name: "Large eggs (18)",
      category: "dairy",
      sizeQty: 18,
      unit: "each",
      sizeLabel: "18 eggs",
      artKey: "eggs",
      aliases: ["large eggs", "18 large eggs"],
      searchQuery: "large eggs 18",
    },
    basePrice: 6.6,
  },
  {
    item: {
      id: "eggs-xl-12",
      name: "Extra large eggs",
      category: "dairy",
      sizeQty: 1,
      unit: "dozen",
      sizeLabel: "12 eggs",
      artKey: "eggs",
      aliases: ["extra large eggs"],
      searchQuery: "extra large eggs 12",
    },
    basePrice: 5.4,
  },
  {
    item: {
      id: "eggs-medium-12",
      name: "Medium eggs",
      category: "dairy",
      sizeQty: 1,
      unit: "dozen",
      sizeLabel: "12 eggs",
      artKey: "eggs",
      aliases: ["medium eggs"],
      searchQuery: "medium eggs 12",
    },
    basePrice: 4.4,
  },
  {
    item: {
      id: "bread-multigrain-675g",
      name: "Multigrain bread",
      category: "bakery",
      sizeQty: 0.675,
      unit: "kg",
      sizeLabel: "675 g",
      artKey: "bread",
      aliases: ["multigrain bread"],
      searchQuery: "multigrain bread 675 g",
    },
    basePrice: 3.9,
  },
  {
    item: {
      id: "bread-rye-450g",
      name: "Rye bread",
      category: "bakery",
      sizeQty: 0.45,
      unit: "kg",
      sizeLabel: "450 g",
      artKey: "bread",
      aliases: ["rye bread"],
      searchQuery: "rye bread 450 g",
    },
    basePrice: 3.8,
  },
  {
    item: {
      id: "english-muffins-6",
      name: "English muffins",
      category: "bakery",
      sizeQty: 6,
      unit: "each",
      sizeLabel: "6 pack",
      artKey: "bagel",
      aliases: ["english muffins", "english muffin"],
      searchQuery: "english muffins 6",
    },
    basePrice: 3.6,
  },
  {
    item: {
      id: "tortillas-10",
      name: "Flour tortillas",
      category: "bakery",
      sizeQty: 10,
      unit: "each",
      sizeLabel: "10 pack",
      artKey: "bread",
      aliases: ["flour tortillas", "tortilla wraps"],
      searchQuery: "flour tortillas 10",
    },
    basePrice: 4.3,
  },
  {
    item: {
      id: "hamburger-buns-8",
      name: "Hamburger buns",
      category: "bakery",
      sizeQty: 8,
      unit: "each",
      sizeLabel: "8 pack",
      artKey: "bread",
      aliases: ["hamburger buns", "burger buns"],
      searchQuery: "hamburger buns 8",
    },
    basePrice: 3.4,
  },
  {
    item: {
      id: "hotdog-buns-8",
      name: "Hot dog buns",
      category: "bakery",
      sizeQty: 8,
      unit: "each",
      sizeLabel: "8 pack",
      artKey: "bread",
      aliases: ["hot dog buns", "hotdog buns"],
      searchQuery: "hot dog buns 8",
    },
    basePrice: 3.3,
  },
  {
    item: {
      id: "pita-6",
      name: "Pita bread",
      category: "bakery",
      sizeQty: 6,
      unit: "each",
      sizeLabel: "6 pack",
      artKey: "bread",
      aliases: ["pita bread", "pita pockets"],
      searchQuery: "pita bread 6",
    },
    basePrice: 3.6,
  },
  {
    item: {
      id: "croissants-6",
      name: "Croissants",
      category: "bakery",
      sizeQty: 6,
      unit: "each",
      sizeLabel: "6 pack",
      artKey: "bread",
      aliases: ["croissants", "croissant"],
      searchQuery: "croissants 6",
    },
    basePrice: 5.6,
  },
  {
    item: {
      id: "dinner-rolls-12",
      name: "Dinner rolls",
      category: "bakery",
      sizeQty: 12,
      unit: "each",
      sizeLabel: "12 pack",
      artKey: "bread",
      aliases: ["dinner rolls"],
      searchQuery: "dinner rolls 12",
    },
    basePrice: 4.6,
  },
  {
    item: {
      id: "flour-ap-5kg",
      name: "All-purpose flour (5 kg)",
      category: "pantry",
      sizeQty: 5,
      unit: "kg",
      sizeLabel: "5 kg",
      artKey: "flour",
      aliases: ["all purpose flour", "all-purpose flour"],
      searchQuery: "all purpose flour 5 kg",
    },
    basePrice: 10.0,
  },
  {
    item: {
      id: "sugar-brown-1kg",
      name: "Brown sugar",
      category: "pantry",
      sizeQty: 1,
      unit: "kg",
      sizeLabel: "1 kg",
      artKey: "sugar",
      aliases: ["brown sugar"],
      searchQuery: "brown sugar 1 kg",
    },
    basePrice: 3.8,
  },
  {
    item: {
      id: "sugar-icing-1kg",
      name: "Icing sugar",
      category: "pantry",
      sizeQty: 1,
      unit: "kg",
      sizeLabel: "1 kg",
      artKey: "sugar",
      aliases: ["icing sugar", "powdered sugar"],
      searchQuery: "icing sugar 1 kg",
    },
    basePrice: 3.6,
  },
  {
    item: {
      id: "sugar-4kg",
      name: "White sugar (4 kg)",
      category: "pantry",
      sizeQty: 4,
      unit: "kg",
      sizeLabel: "4 kg",
      artKey: "sugar",
      aliases: ["white sugar", "granulated sugar", "sugar"],
      searchQuery: "white sugar 4 kg",
    },
    basePrice: 6.8,
  },
  {
    item: {
      id: "honey-500g",
      name: "Liquid honey",
      category: "pantry",
      sizeQty: 0.5,
      unit: "kg",
      sizeLabel: "500 g",
      artKey: "jar",
      aliases: ["honey", "liquid honey"],
      searchQuery: "liquid honey 500 g",
    },
    basePrice: 8.5,
  },
  {
    item: {
      id: "maple-syrup-540ml",
      name: "Maple syrup",
      category: "pantry",
      sizeQty: 0.54,
      unit: "L",
      sizeLabel: "540 mL",
      artKey: "jar",
      aliases: ["maple syrup"],
      searchQuery: "maple syrup 540 mL",
    },
    basePrice: 11.0,
  },
  {
    item: {
      id: "salt-table-1kg",
      name: "Table salt",
      category: "pantry",
      sizeQty: 1,
      unit: "kg",
      sizeLabel: "1 kg",
      artKey: "generic",
      aliases: ["table salt"],
      searchQuery: "table salt 1 kg",
    },
    basePrice: 2.2,
  },
  {
    item: {
      id: "oats-quick-1kg",
      name: "Quick oats",
      category: "pantry",
      sizeQty: 1,
      unit: "kg",
      sizeLabel: "1 kg",
      artKey: "oats",
      aliases: ["quick oats"],
      searchQuery: "quick oats 1 kg",
    },
    basePrice: 4.0,
  },
  {
    item: {
      id: "rice-brown-2kg",
      name: "Brown rice",
      category: "pantry",
      sizeQty: 2,
      unit: "kg",
      sizeLabel: "2 kg",
      artKey: "rice",
      aliases: ["brown rice"],
      searchQuery: "brown rice 2 kg",
    },
    basePrice: 6.6,
  },
  {
    item: {
      id: "rice-basmati-2kg",
      name: "Basmati rice",
      category: "pantry",
      sizeQty: 2,
      unit: "kg",
      sizeLabel: "2 kg",
      artKey: "rice",
      aliases: ["basmati rice"],
      searchQuery: "basmati rice 2 kg",
    },
    basePrice: 9.5,
  },
  {
    item: {
      id: "rice-long-2kg",
      name: "Long grain white rice (2 kg)",
      category: "pantry",
      sizeQty: 2,
      unit: "kg",
      sizeLabel: "2 kg",
      artKey: "rice",
      aliases: ["long grain rice", "long grain white rice"],
      searchQuery: "long grain rice 2 kg",
    },
    basePrice: 5.6,
  },
  {
    item: {
      id: "macaroni-900g",
      name: "Elbow macaroni",
      category: "pantry",
      sizeQty: 0.9,
      unit: "kg",
      sizeLabel: "900 g",
      artKey: "pasta",
      aliases: ["elbow macaroni", "macaroni"],
      searchQuery: "elbow macaroni 900 g",
    },
    basePrice: 2.4,
  },
  {
    item: {
      id: "rotini-900g",
      name: "Rotini",
      category: "pantry",
      sizeQty: 0.9,
      unit: "kg",
      sizeLabel: "900 g",
      artKey: "pasta",
      aliases: ["rotini", "rotini pasta"],
      searchQuery: "rotini 900 g",
    },
    basePrice: 2.4,
  },
  {
    item: {
      id: "tomato-paste-156ml",
      name: "Tomato paste",
      category: "pantry",
      sizeQty: 0.156,
      unit: "L",
      sizeLabel: "156 mL",
      artKey: "can",
      aliases: ["tomato paste"],
      searchQuery: "tomato paste 156 mL",
    },
    basePrice: 1.9,
  },
  {
    item: {
      id: "tomatoes-crushed-796ml",
      name: "Crushed tomatoes",
      category: "pantry",
      sizeQty: 0.796,
      unit: "L",
      sizeLabel: "796 mL",
      artKey: "can",
      aliases: ["crushed tomatoes"],
      searchQuery: "crushed tomatoes 796 mL",
    },
    basePrice: 2.6,
  },
  {
    item: {
      id: "kidney-beans-540ml",
      name: "Kidney beans",
      category: "pantry",
      sizeQty: 0.54,
      unit: "L",
      sizeLabel: "540 mL",
      artKey: "can",
      aliases: ["kidney beans"],
      searchQuery: "kidney beans 540 mL",
    },
    basePrice: 1.7,
  },
  {
    item: {
      id: "chickpeas-540ml",
      name: "Chickpeas",
      category: "pantry",
      sizeQty: 0.54,
      unit: "L",
      sizeLabel: "540 mL",
      artKey: "can",
      aliases: ["chickpeas", "garbanzo beans"],
      searchQuery: "chickpeas 540 mL",
    },
    basePrice: 1.7,
  },
  {
    item: {
      id: "corn-canned-341ml",
      name: "Canned corn",
      category: "pantry",
      sizeQty: 0.341,
      unit: "L",
      sizeLabel: "341 mL",
      artKey: "can",
      aliases: ["canned corn", "whole kernel corn"],
      searchQuery: "canned corn 341 mL",
    },
    basePrice: 1.8,
  },
  {
    item: {
      id: "tuna-canned-170g",
      name: "Canned tuna",
      category: "pantry",
      sizeQty: 0.17,
      unit: "kg",
      sizeLabel: "170 g",
      artKey: "can",
      aliases: ["canned tuna", "chunk light tuna"],
      searchQuery: "canned tuna 170 g",
    },
    basePrice: 2.4,
  },
  {
    item: {
      id: "beef-broth-900ml",
      name: "Beef broth",
      category: "pantry",
      sizeQty: 0.9,
      unit: "L",
      sizeLabel: "900 mL",
      artKey: "carton",
      aliases: ["beef broth"],
      searchQuery: "beef broth 900 mL",
    },
    basePrice: 2.8,
  },
  {
    item: {
      id: "veg-broth-900ml",
      name: "Vegetable broth",
      category: "pantry",
      sizeQty: 0.9,
      unit: "L",
      sizeLabel: "900 mL",
      artKey: "carton",
      aliases: ["vegetable broth"],
      searchQuery: "vegetable broth 900 mL",
    },
    basePrice: 2.8,
  },
  {
    item: {
      id: "ketchup-1l",
      name: "Ketchup",
      category: "pantry",
      sizeQty: 1,
      unit: "L",
      sizeLabel: "1 L",
      artKey: "jar",
      aliases: ["ketchup", "tomato ketchup"],
      searchQuery: "ketchup 1 L",
    },
    basePrice: 4.2,
  },
  {
    item: {
      id: "mayo-890ml",
      name: "Mayonnaise",
      category: "pantry",
      sizeQty: 0.89,
      unit: "L",
      sizeLabel: "890 mL",
      artKey: "jar",
      aliases: ["mayonnaise", "mayo"],
      searchQuery: "mayonnaise 890 mL",
    },
    basePrice: 6.2,
  },
  {
    item: {
      id: "olive-oil-1l",
      name: "Olive oil",
      category: "pantry",
      sizeQty: 1,
      unit: "L",
      sizeLabel: "1 L",
      artKey: "oil",
      aliases: ["olive oil", "extra virgin olive oil"],
      searchQuery: "olive oil 1 L",
    },
    basePrice: 13.0,
  },
  {
    item: {
      id: "vegetable-oil-3l",
      name: "Vegetable oil",
      category: "pantry",
      sizeQty: 3,
      unit: "L",
      sizeLabel: "3 L",
      artKey: "oil",
      aliases: ["vegetable oil"],
      searchQuery: "vegetable oil 3 L",
    },
    basePrice: 10.0,
  },
  {
    item: {
      id: "vinegar-white-1l",
      name: "White vinegar",
      category: "pantry",
      sizeQty: 1,
      unit: "L",
      sizeLabel: "1 L",
      artKey: "jar",
      aliases: ["white vinegar"],
      searchQuery: "white vinegar 1 L",
    },
    basePrice: 2.6,
  },
  {
    item: {
      id: "soy-sauce-1l",
      name: "Soy sauce",
      category: "pantry",
      sizeQty: 1,
      unit: "L",
      sizeLabel: "1 L",
      artKey: "jar",
      aliases: ["soy sauce"],
      searchQuery: "soy sauce 1 L",
    },
    basePrice: 5.0,
  },
  {
    item: {
      id: "coffee-ground-340g",
      name: "Ground coffee",
      category: "pantry",
      sizeQty: 0.34,
      unit: "kg",
      sizeLabel: "340 g",
      artKey: "jar",
      aliases: ["ground coffee"],
      searchQuery: "ground coffee 340 g",
    },
    basePrice: 9.0,
  },
  {
    item: {
      id: "juice-orange-1-75l",
      name: "Orange juice",
      category: "pantry",
      sizeQty: 1.75,
      unit: "L",
      sizeLabel: "1.75 L",
      artKey: "carton",
      aliases: ["orange juice"],
      searchQuery: "orange juice 1.75 L",
    },
    basePrice: 4.6,
  },
  {
    item: {
      id: "juice-apple-1-89l",
      name: "Apple juice",
      category: "pantry",
      sizeQty: 1.89,
      unit: "L",
      sizeLabel: "1.89 L",
      artKey: "carton",
      aliases: ["apple juice"],
      searchQuery: "apple juice 1.89 L",
    },
    basePrice: 3.9,
  },
  {
    item: {
      id: "oranges-navel-kg",
      name: "Navel oranges",
      category: "produce",
      sizeQty: 1,
      unit: "kg",
      sizeLabel: "per kg",
      artKey: "generic",
      aliases: ["navel oranges", "navel orange", "oranges"],
      searchQuery: "navel oranges",
    },
    basePrice: 3.8,
    seasonal: true,
  },
  {
    item: {
      id: "lemons-each",
      name: "Lemons",
      category: "produce",
      sizeQty: 1,
      unit: "each",
      sizeLabel: "each",
      artKey: "generic",
      aliases: ["lemon", "lemons"],
      searchQuery: "lemons",
    },
    basePrice: 0.99,
  },
  {
    item: {
      id: "limes-each",
      name: "Limes",
      category: "produce",
      sizeQty: 1,
      unit: "each",
      sizeLabel: "each",
      artKey: "generic",
      aliases: ["lime", "limes"],
      searchQuery: "limes",
    },
    basePrice: 0.69,
  },
  {
    item: {
      id: "pears-kg",
      name: "Pears",
      category: "produce",
      sizeQty: 1,
      unit: "kg",
      sizeLabel: "per kg",
      artKey: "apple",
      aliases: ["pears", "pear", "bartlett pears"],
      searchQuery: "pears",
    },
    basePrice: 4.6,
    seasonal: true,
  },
  {
    item: {
      id: "grapes-red-kg",
      name: "Red grapes",
      category: "produce",
      sizeQty: 1,
      unit: "kg",
      sizeLabel: "per kg",
      artKey: "berries",
      aliases: ["red grapes", "red seedless grapes", "seedless red grapes"],
      searchQuery: "red grapes",
    },
    basePrice: 6.8,
    seasonal: true,
  },
  {
    item: {
      id: "pineapple-each",
      name: "Pineapple",
      category: "produce",
      sizeQty: 1,
      unit: "each",
      sizeLabel: "each",
      artKey: "generic",
      aliases: ["pineapple", "fresh pineapple"],
      searchQuery: "pineapple",
    },
    basePrice: 4.5,
  },
  {
    item: {
      id: "mango-each",
      name: "Mangoes",
      category: "produce",
      sizeQty: 1,
      unit: "each",
      sizeLabel: "each",
      artKey: "generic",
      aliases: ["mango", "mangoes", "ataulfo mango"],
      searchQuery: "mangoes",
    },
    basePrice: 1.8,
    seasonal: true,
  },
  {
    item: {
      id: "cauliflower-each",
      name: "Cauliflower",
      category: "produce",
      sizeQty: 1,
      unit: "each",
      sizeLabel: "each",
      artKey: "broccoli",
      aliases: ["cauliflower", "cauliflower head"],
      searchQuery: "cauliflower",
    },
    basePrice: 4.4,
  },
  {
    item: {
      id: "celery-each",
      name: "Celery",
      category: "produce",
      sizeQty: 1,
      unit: "each",
      sizeLabel: "each",
      artKey: "lettuce",
      aliases: ["celery", "celery stalks"],
      searchQuery: "celery",
    },
    basePrice: 3.2,
  },
  {
    item: {
      id: "cabbage-green-kg",
      name: "Green cabbage",
      category: "produce",
      sizeQty: 1,
      unit: "kg",
      sizeLabel: "per kg",
      artKey: "lettuce",
      aliases: ["green cabbage", "cabbage"],
      searchQuery: "green cabbage",
    },
    basePrice: 2.6,
  },
  {
    item: {
      id: "peppers-red-each",
      name: "Red pepper",
      category: "produce",
      sizeQty: 1,
      unit: "each",
      sizeLabel: "each",
      artKey: "tomato",
      aliases: ["red pepper", "red bell pepper", "red peppers"],
      searchQuery: "red pepper",
    },
    basePrice: 1.9,
    seasonal: true,
  },
  {
    item: {
      id: "peppers-green-each",
      name: "Green pepper",
      category: "produce",
      sizeQty: 1,
      unit: "each",
      sizeLabel: "each",
      artKey: "cucumber",
      aliases: ["green pepper", "green bell pepper", "green peppers"],
      searchQuery: "green pepper",
    },
    basePrice: 1.6,
    seasonal: true,
  },
  {
    item: {
      id: "mushrooms-white-227g",
      name: "White mushrooms",
      category: "produce",
      sizeQty: 0.227,
      unit: "kg",
      sizeLabel: "227 g",
      artKey: "generic",
      aliases: ["white mushrooms", "button mushrooms"],
      searchQuery: "white mushrooms 227 g",
    },
    basePrice: 3.0,
  },
  {
    item: {
      id: "spinach-baby-312g",
      name: "Baby spinach",
      category: "produce",
      sizeQty: 0.312,
      unit: "kg",
      sizeLabel: "312 g",
      artKey: "lettuce",
      aliases: ["baby spinach", "spinach"],
      searchQuery: "baby spinach 312 g",
    },
    basePrice: 4.3,
  },
  {
    item: {
      id: "garlic-each",
      name: "Garlic",
      category: "produce",
      sizeQty: 1,
      unit: "each",
      sizeLabel: "each",
      artKey: "onion",
      aliases: ["garlic", "garlic bulb"],
      searchQuery: "garlic",
    },
    basePrice: 0.99,
  },
  {
    item: {
      id: "sweet-potatoes-kg",
      name: "Sweet potatoes",
      category: "produce",
      sizeQty: 1,
      unit: "kg",
      sizeLabel: "per kg",
      artKey: "potato",
      aliases: ["sweet potatoes", "sweet potato"],
      searchQuery: "sweet potatoes",
    },
    basePrice: 3.4,
  },
  {
    item: {
      id: "zucchini-kg",
      name: "Zucchini",
      category: "produce",
      sizeQty: 1,
      unit: "kg",
      sizeLabel: "per kg",
      artKey: "cucumber",
      aliases: ["zucchini", "green zucchini"],
      searchQuery: "zucchini",
    },
    basePrice: 3.4,
    seasonal: true,
  },
  {
    item: {
      id: "lettuce-iceberg-each",
      name: "Iceberg lettuce",
      category: "produce",
      sizeQty: 1,
      unit: "each",
      sizeLabel: "each",
      artKey: "lettuce",
      aliases: ["iceberg lettuce", "lettuce iceberg"],
      searchQuery: "iceberg lettuce",
    },
    basePrice: 2.9,
  },
  {
    item: {
      id: "green-onions-each",
      name: "Green onions",
      category: "produce",
      sizeQty: 1,
      unit: "each",
      sizeLabel: "each",
      artKey: "onion",
      aliases: ["green onions", "green onion", "scallions"],
      searchQuery: "green onions",
    },
    basePrice: 1.3,
  },
  {
    item: {
      id: "tomatoes-vine-kg",
      name: "Vine tomatoes",
      category: "produce",
      sizeQty: 1,
      unit: "kg",
      sizeLabel: "per kg",
      artKey: "tomato",
      aliases: ["vine tomatoes", "tomatoes on the vine", "vine ripened tomatoes"],
      searchQuery: "vine tomatoes",
    },
    basePrice: 4.8,
    seasonal: true,
  },
  {
    item: {
      id: "apples-honeycrisp-kg",
      name: "Honeycrisp apples",
      category: "produce",
      sizeQty: 1,
      unit: "kg",
      sizeLabel: "per kg",
      artKey: "apple",
      aliases: ["honeycrisp apples", "honeycrisp apple", "honeycrisp"],
      searchQuery: "honeycrisp apples",
    },
    basePrice: 5.8,
    seasonal: true,
  },
  {
    item: {
      id: "apples-granny-kg",
      name: "Granny Smith apples",
      category: "produce",
      sizeQty: 1,
      unit: "kg",
      sizeLabel: "per kg",
      artKey: "apple",
      aliases: ["granny smith apples", "granny smith apple"],
      searchQuery: "granny smith apples",
    },
    basePrice: 4.4,
    seasonal: true,
  },
  {
    item: {
      id: "ginger-kg",
      name: "Ginger",
      category: "produce",
      sizeQty: 1,
      unit: "kg",
      sizeLabel: "per kg",
      artKey: "generic",
      aliases: ["ginger", "ginger root"],
      searchQuery: "ginger",
    },
    basePrice: 8.0,
  },
  {
    item: {
      id: "kale-each",
      name: "Kale",
      category: "produce",
      sizeQty: 1,
      unit: "each",
      sizeLabel: "each",
      artKey: "lettuce",
      aliases: ["kale", "green kale"],
      searchQuery: "kale",
    },
    basePrice: 2.8,
  },
  {
    item: {
      id: "onions-red-kg",
      name: "Red onions",
      category: "produce",
      sizeQty: 1,
      unit: "kg",
      sizeLabel: "per kg",
      artKey: "onion",
      aliases: ["red onions", "red onion"],
      searchQuery: "red onions",
    },
    basePrice: 3.2,
  },
];

export const ITEMS: Item[] = [...SEED_ITEMS.map((s) => s.item), ...EXPANDED_ITEMS];