import type { Item } from "../types";
import type { SeedItem } from "./types";

export const SEED_ITEMS: SeedItem[] = [
  // Dairy (10 items)
  {
    item: {
      id: "milk-2pct-4l",
      name: "2% milk",
      category: "dairy",
      sizeQty: 4,
      unit: "L",
      sizeLabel: "4 L",
      artKey: "milk",
      aliases: ["2% milk", "milk", "2 percent milk", "partly skimmed milk"],
      searchQuery: "2% milk 4 L",
    },
    basePrice: 6.39,
  },
  {
    item: {
      id: "milk-homo-2l",
      name: "Homogenized milk",
      category: "dairy",
      sizeQty: 2,
      unit: "L",
      sizeLabel: "2 L",
      artKey: "milk",
      aliases: ["homo milk", "homogenized milk", "whole milk", "3.25% milk"],
      searchQuery: "homogenized milk 2 L",
    },
    basePrice: 4.79,
  },
  {
    item: {
      id: "butter-salted-454g",
      name: "Salted butter",
      category: "dairy",
      sizeQty: 0.454,
      unit: "kg",
      sizeLabel: "454 g",
      artKey: "butter",
      aliases: ["butter", "salted butter", "butter brick"],
      searchQuery: "salted butter 454 g",
    },
    basePrice: 6.1,
    saleProfile: { saveon: "perpetual" },
  },
  {
    item: {
      id: "eggs-large-12",
      name: "Large eggs",
      category: "dairy",
      sizeQty: 1,
      unit: "dozen",
      sizeLabel: "dozen",
      artKey: "eggs",
      aliases: ["eggs", "large eggs", "dozen eggs", "white eggs"],
      searchQuery: "large eggs 12",
    },
    basePrice: 4.6,
  },
  {
    item: {
      id: "cheddar-old-400g",
      name: "Old cheddar",
      category: "dairy",
      sizeQty: 0.4,
      unit: "kg",
      sizeLabel: "400 g",
      artKey: "cheese",
      aliases: ["cheddar", "old cheddar", "cheese block", "cheddar cheese"],
      searchQuery: "old cheddar cheese 400 g",
    },
    basePrice: 7.49,
  },
  {
    item: {
      id: "mozzarella-340g",
      name: "Mozzarella",
      category: "dairy",
      sizeQty: 0.34,
      unit: "kg",
      sizeLabel: "340 g",
      artKey: "cheese",
      aliases: ["mozzarella", "mozzarella cheese", "pizza cheese"],
      searchQuery: "mozzarella cheese 340 g",
    },
    basePrice: 5.99,
  },
  {
    item: {
      id: "greek-yogurt-plain",
      name: "Plain Greek yogurt",
      category: "dairy",
      sizeQty: 0.5,
      unit: "kg",
      sizeLabel: "500 g",
      artKey: "yogurt",
      aliases: ["greek yogurt", "plain greek yogurt", "plain yogurt"],
      searchQuery: "plain greek yogurt 500 g",
    },
    basePrice: 6.1,
  },
  {
    item: {
      id: "yogurt-vanilla-650g",
      name: "Vanilla yogurt",
      category: "dairy",
      sizeQty: 0.65,
      unit: "kg",
      sizeLabel: "650 g",
      artKey: "yogurt",
      aliases: ["vanilla yogurt", "yogurt", "vanilla tub"],
      searchQuery: "vanilla yogurt 650 g",
    },
    basePrice: 4.49,
  },
  {
    item: {
      id: "sour-cream-500ml",
      name: "Sour cream",
      category: "dairy",
      sizeQty: 0.5,
      unit: "L",
      sizeLabel: "500 mL",
      artKey: "sourcream",
      aliases: ["sour cream", "14% sour cream", "crema"],
      searchQuery: "sour cream 500 mL",
    },
    basePrice: 3.49,
  },
  {
    item: {
      id: "cream-cheese-250g",
      name: "Cream cheese",
      category: "dairy",
      sizeQty: 0.25,
      unit: "kg",
      sizeLabel: "250 g",
      artKey: "butter",
      aliases: ["cream cheese", "cream cheese brick", "spreadable cream cheese"],
      searchQuery: "cream cheese 250 g",
    },
    basePrice: 4.29,
  },

  // Bakery (8 items)
  {
    item: {
      id: "flour-ap-10kg",
      name: "All-purpose flour",
      category: "bakery",
      sizeQty: 10,
      unit: "kg",
      sizeLabel: "10 kg",
      artKey: "flour",
      aliases: ["flour", "all purpose flour", "white flour", "ap flour"],
      searchQuery: "all purpose flour 10 kg",
    },
    basePrice: 18.5,
  },
  {
    item: {
      id: "flour-ap-2-5kg",
      name: "All-purpose flour",
      category: "bakery",
      sizeQty: 2.5,
      unit: "kg",
      sizeLabel: "2.5 kg",
      artKey: "flour",
      aliases: ["flour", "all purpose flour", "white flour", "ap flour 2.5kg"],
      searchQuery: "all purpose flour 2.5 kg",
    },
    basePrice: 6.49,
  },
  {
    item: {
      id: "flour-ww-2-5kg",
      name: "Whole wheat flour",
      category: "bakery",
      sizeQty: 2.5,
      unit: "kg",
      sizeLabel: "2.5 kg",
      artKey: "flour",
      aliases: ["whole wheat flour", "ww flour", "wheat flour"],
      searchQuery: "whole wheat flour 2.5 kg",
    },
    basePrice: 6.99,
  },
  {
    item: {
      id: "bread-white-675g",
      name: "White sandwich bread",
      category: "bakery",
      sizeQty: 0.675,
      unit: "kg",
      sizeLabel: "675 g",
      artKey: "bread",
      aliases: ["white bread", "sandwich bread", "sliced bread"],
      searchQuery: "white sandwich bread 675 g",
    },
    basePrice: 3.29,
  },
  {
    item: {
      id: "bread-ww-675g",
      name: "Whole wheat bread",
      category: "bakery",
      sizeQty: 0.675,
      unit: "kg",
      sizeLabel: "675 g",
      artKey: "bread",
      aliases: ["whole wheat bread", "brown bread", "wheat bread"],
      searchQuery: "whole wheat bread 675 g",
    },
    basePrice: 3.49,
  },
  {
    item: {
      id: "sugar-2kg",
      name: "Granulated sugar",
      category: "bakery",
      sizeQty: 2,
      unit: "kg",
      sizeLabel: "2 kg",
      artKey: "sugar",
      aliases: ["sugar", "white sugar", "granulated sugar"],
      searchQuery: "granulated white sugar 2 kg",
    },
    basePrice: 3.99,
  },
  {
    item: {
      id: "oats-1kg",
      name: "Large flake oats",
      category: "bakery",
      sizeQty: 1,
      unit: "kg",
      sizeLabel: "1 kg",
      artKey: "oats",
      aliases: ["oats", "rolled oats", "large flake oats", "oatmeal"],
      searchQuery: "large flake oats 1 kg",
    },
    basePrice: 3.79,
  },
  {
    item: {
      id: "bagels-6",
      name: "Plain bagels",
      category: "bakery",
      sizeQty: 6,
      unit: "each",
      sizeLabel: "6 pack",
      artKey: "bagel",
      aliases: ["bagels", "plain bagels", "6 pack bagels"],
      searchQuery: "plain bagels 6 pack",
    },
    basePrice: 3.99,
  },

  // Pantry (10 items)
  {
    item: {
      id: "spaghetti-900g",
      name: "Spaghetti",
      category: "pantry",
      sizeQty: 0.9,
      unit: "kg",
      sizeLabel: "900 g",
      artKey: "pasta",
      aliases: ["spaghetti", "pasta", "noodles"],
      searchQuery: "spaghetti 900 g",
    },
    basePrice: 2.55,
  },
  {
    item: {
      id: "penne-900g",
      name: "Penne",
      category: "pantry",
      sizeQty: 0.9,
      unit: "kg",
      sizeLabel: "900 g",
      artKey: "pasta",
      aliases: ["penne", "penne rigate", "pasta"],
      searchQuery: "penne rigate 900 g",
    },
    basePrice: 2.55,
  },
  {
    item: {
      id: "rice-long-8kg",
      name: "Long grain rice",
      category: "pantry",
      sizeQty: 8,
      unit: "kg",
      sizeLabel: "8 kg",
      artKey: "rice",
      aliases: ["rice", "white rice", "long grain rice"],
      searchQuery: "white long grain rice 8 kg",
    },
    basePrice: 17.99,
  },
  {
    item: {
      id: "rice-jasmine-8kg",
      name: "Jasmine rice",
      category: "pantry",
      sizeQty: 8,
      unit: "kg",
      sizeLabel: "8 kg",
      artKey: "rice",
      aliases: ["jasmine rice", "thai jasmine rice", "fragrant rice", "rice"],
      searchQuery: "jasmine rice 8 kg",
    },
    basePrice: 19.99,
  },
  {
    item: {
      id: "canola-oil-3l",
      name: "Canola oil",
      category: "pantry",
      sizeQty: 3,
      unit: "L",
      sizeLabel: "3 L",
      artKey: "oil",
      aliases: ["canola oil", "cooking oil", "vegetable oil"],
      searchQuery: "canola oil 3 L",
    },
    basePrice: 9.99,
  },
  {
    item: {
      id: "peanut-butter-1kg",
      name: "Peanut butter",
      category: "pantry",
      sizeQty: 1,
      unit: "kg",
      sizeLabel: "1 kg",
      artKey: "jar",
      aliases: ["peanut butter", "smooth peanut butter", "pb"],
      searchQuery: "smooth peanut butter 1 kg",
    },
    basePrice: 6.49,
  },
  {
    item: {
      id: "tomatoes-canned-796ml",
      name: "Diced tomatoes",
      category: "pantry",
      sizeQty: 0.796,
      unit: "L",
      sizeLabel: "796 mL",
      artKey: "can",
      aliases: ["canned tomatoes", "diced tomatoes", "tomatoes"],
      searchQuery: "diced tomatoes 796 mL",
    },
    basePrice: 1.99,
  },
  {
    item: {
      id: "black-beans-540ml",
      name: "Black beans",
      category: "pantry",
      sizeQty: 0.54,
      unit: "L",
      sizeLabel: "540 mL",
      artKey: "can",
      aliases: ["black beans", "canned beans", "frijoles"],
      searchQuery: "black beans 540 mL",
    },
    basePrice: 1.49,
  },
  {
    item: {
      id: "pasta-sauce-650ml",
      name: "Tomato pasta sauce",
      category: "pantry",
      sizeQty: 0.65,
      unit: "L",
      sizeLabel: "650 mL",
      artKey: "jar",
      aliases: ["pasta sauce", "marinara", "tomato sauce", "spaghetti sauce"],
      searchQuery: "tomato pasta sauce 650 mL",
    },
    basePrice: 2.99,
  },
  {
    item: {
      id: "chicken-broth-900ml",
      name: "Chicken broth",
      category: "pantry",
      sizeQty: 0.9,
      unit: "L",
      sizeLabel: "900 mL",
      artKey: "carton",
      aliases: ["chicken broth", "chicken stock", "broth"],
      searchQuery: "chicken broth 900 mL",
    },
    basePrice: 2.49,
  },

  // Produce (12 items)
  {
    item: {
      id: "bananas-kg",
      name: "Bananas",
      category: "produce",
      sizeQty: 1,
      unit: "kg",
      sizeLabel: "per kg",
      artKey: "banana",
      aliases: ["bananas", "banana", "yellow bananas"],
      searchQuery: "bananas",
    },
    basePrice: 1.7,
  },
  {
    item: {
      id: "apples-gala-kg",
      name: "Gala apples",
      category: "produce",
      sizeQty: 1,
      unit: "kg",
      sizeLabel: "per kg",
      artKey: "apple",
      aliases: ["apples", "gala apples", "red apples"],
      searchQuery: "gala apples",
    },
    basePrice: 4.39,
  },
  {
    item: {
      id: "carrots-907g",
      name: "Carrots",
      category: "produce",
      sizeQty: 0.907,
      unit: "kg",
      sizeLabel: "2 lb bag",
      artKey: "carrot",
      aliases: ["carrots", "whole carrots", "bag of carrots"],
      searchQuery: "carrots 2 lb",
    },
    basePrice: 2.49,
  },
  {
    item: {
      id: "potatoes-russet-4-54kg",
      name: "Russet potatoes",
      category: "produce",
      sizeQty: 4.54,
      unit: "kg",
      sizeLabel: "10 lb bag",
      artKey: "potato",
      aliases: ["potatoes", "russet potatoes", "baking potatoes"],
      searchQuery: "russet potatoes 10 lb",
    },
    basePrice: 5.99,
  },
  {
    item: {
      id: "onions-yellow-1-36kg",
      name: "Yellow onions",
      category: "produce",
      sizeQty: 1.36,
      unit: "kg",
      sizeLabel: "3 lb bag",
      artKey: "onion",
      aliases: ["onions", "yellow onions", "cooking onions"],
      searchQuery: "yellow onions 3 lb",
    },
    basePrice: 3.49,
  },
  {
    item: {
      id: "tomatoes-roma-kg",
      name: "Roma tomatoes",
      category: "produce",
      sizeQty: 1,
      unit: "kg",
      sizeLabel: "per kg",
      artKey: "tomato",
      aliases: ["roma tomatoes", "plum tomatoes", "tomatoes"],
      searchQuery: "roma tomatoes",
    },
    basePrice: 4.39,
  },
  {
    item: {
      id: "romaine-3",
      name: "Romaine hearts",
      category: "produce",
      sizeQty: 3,
      unit: "each",
      sizeLabel: "3 pack",
      artKey: "lettuce",
      aliases: ["romaine hearts", "lettuce", "romaine lettuce"],
      searchQuery: "romaine hearts 3 pack",
    },
    basePrice: 4.49,
  },
  {
    item: {
      id: "strawberries-454g",
      name: "Strawberries",
      category: "produce",
      sizeQty: 0.454,
      unit: "kg",
      sizeLabel: "454 g",
      artKey: "berries",
      aliases: ["strawberries", "fresh strawberries", "berries"],
      searchQuery: "fresh strawberries 454 g",
    },
    basePrice: 4.6,
    seasonal: true,
  },
  {
    item: {
      id: "blueberries-510g",
      name: "Blueberries",
      category: "produce",
      sizeQty: 0.51,
      unit: "kg",
      sizeLabel: "510 g",
      artKey: "berries",
      aliases: ["blueberries", "fresh blueberries", "berries"],
      searchQuery: "fresh blueberries 510 g",
    },
    basePrice: 5.99,
    seasonal: true,
  },
  {
    item: {
      id: "broccoli-kg",
      name: "Broccoli crowns",
      category: "produce",
      sizeQty: 1,
      unit: "kg",
      sizeLabel: "per kg",
      artKey: "broccoli",
      aliases: ["broccoli", "broccoli crowns", "fresh broccoli"],
      searchQuery: "broccoli crowns",
    },
    basePrice: 4.39,
  },
  {
    item: {
      id: "cucumber-english",
      name: "English cucumber",
      category: "produce",
      sizeQty: 1,
      unit: "each",
      sizeLabel: "each",
      artKey: "cucumber",
      aliases: ["cucumber", "english cucumber", "long english cucumber"],
      searchQuery: "english cucumber",
    },
    basePrice: 1.79,
  },
  {
    item: {
      id: "avocados-4",
      name: "Avocados",
      category: "produce",
      sizeQty: 4,
      unit: "each",
      sizeLabel: "4 pack",
      artKey: "avocado",
      aliases: ["avocados", "haas avocados", "bag of avocados"],
      searchQuery: "avocados 4 pack",
    },
    basePrice: 4.99,
  },
];

export const ITEMS: Item[] = SEED_ITEMS.map((s) => s.item);